---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-15.04

suites:
  - name: default
    run_list:
      - recipe[skype-daemon::default]
    attributes:
      skype-daemon:
        app-name: Skype4Java
        username: <%= ENV['SKYPE_USERNAME'] %>
        password: <%= ENV['SKYPE_PASSWORD'] %>
